name: Maven Publish
on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
    secrets:
      signingKeyId:
        required: true
      signingPassword:
        required: true
      signingKey:
        required: true
      sonatypeUsername:
        required: true
      sonatypePassword:
        required: true

jobs:
  check-update:
    runs-on: ubuntu-latest
    env:
      HMCL_UPDATE_CHANNEL: ${{ inputs.channel }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Publish to Maven Central
        run: ./gradlew --no-daemon --info upload -Phmcl.channel=$HMCL_UPDATE_CHANNEL
        env:
          SIGNING_KEY_ID: ${{ secrets.signingKeyId }}
          SIGNING_PASSWORD: ${{ secrets.signingPassword }}
          SIGNING_KEY: ${{ secrets.signingKey }}
          SONATYPE_USERNAME: ${{ secrets.sonatypeUsername }}
          SONATYPE_PASSWORD: ${{ secrets.sonatypePassword }}
